services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pokemoncenter-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PokemonCenter@2026"
    ports:
      - "1433:1433"
    restart: unless-stopped
